orchestratorConfig:
  testConfig:
  - testToLaunch: test1
    silentMode: true
  - testToLaunch: test2
  - testToLaunch: test3
  - testToLaunch: test4
  - testToLaunch: test5
  - testToLaunch: test6
    silentMode: true